// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUaC-x_cnwISdE98apodP-KsOaK_SxrP0',
    appId: '1:294768327918:web:d2d64bbef323650f1387ff',
    messagingSenderId: '294768327918',
    projectId: 'fir-messaging-43a48',
    authDomain: 'fir-messaging-43a48.firebaseapp.com',
    storageBucket: 'fir-messaging-43a48.appspot.com',
    measurementId: 'G-0X6ZWNVYGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWs5YKvayyHcWGzyLd0ZS_9-U7P7yycx0',
    appId: '1:294768327918:android:e63c3cbfb1a665811387ff',
    messagingSenderId: '294768327918',
    projectId: 'fir-messaging-43a48',
    storageBucket: 'fir-messaging-43a48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGJPSxeNlomoJEybH2-NSVgM9Qqdhzr4',
    appId: '1:294768327918:ios:9b3d203018dddd941387ff',
    messagingSenderId: '294768327918',
    projectId: 'fir-messaging-43a48',
    storageBucket: 'fir-messaging-43a48.appspot.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJGJPSxeNlomoJEybH2-NSVgM9Qqdhzr4',
    appId: '1:294768327918:ios:cd248d36193f58831387ff',
    messagingSenderId: '294768327918',
    projectId: 'fir-messaging-43a48',
    storageBucket: 'fir-messaging-43a48.appspot.com',
    iosBundleId: 'com.example.firebaseNotification.RunnerTests',
  );
}
